spring:
  application:
    name: single-login
  session:
    timeout: 86400
  # 配置Redis
  data:
    redis:
      port: 6379
      host: localhost
      database: 1
      timeout: # PT2H30M 设置session的过期时间为2h30min